export const REFETCH_MAIN_TRANSACTION_TABLE_DATA: string =
  "EVT_BUS_FNC002_001_REFETCH_MAIN_TRANSACTION_TABLE_DATA";

export const SEND_TRANSACTION_TO_EDIT: string =
  "EVT_BUS_FNC002_002_SEND_TRANSACTION_TO_EDIT";
